### ISSUE TITLE
[Feature Request] 建议添加对加密歌曲密钥文件的相关Hook解密

### ISSUE THREAD

**Issue by SheepChef** [Xposed-Modules-Repo/me.kofua.qmhelper#1]
如题，QQ音乐有许多加密格式，譬如mgg, mflac, qmcX。其解密密钥被置于文件末尾并被二次加密，二次加密密钥需要联网获取，在不执行中间人攻击的前提下，可以通过xposed获取密钥，希望能够添加此功能。

**Comment by zjns** [comment]
有没有可能已经有了。

**Comment by SheepChef** [comment]
> 有没有可能已经有了。

请问，哪次提交是您陈述中的呢？

**Comment by zjns** [comment]
https://github.com/zjns/QMHelper/commit/33271a271c1dde7048835c191991db57c63fe0b0
